# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Ant@1
  inputs:
    buildFile: 'Ant deploy/build.xml'
    options: '-Dsf.dest.username=$(sf.dest.username) -Dsf.dest.password=$(sf.dest.password) -Dsf.dest.serverUrl=$(sf.dest.serverUrl) -Dsf.source.version=$(sf.source.version) -Dsf.dest.version=$(sf.dest.version) -Dsf.maxPoll=$(sf.maxPoll) -Dsf.checkOnly=$(sf.checkOnly) -Dsf.testLevel=$(sf.testLevel)'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'